Lint/Eval:
  Enabled: false


Metrics/LineLength:
  Max: 100


Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines



Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

